# An Alertmanager configuration that forwards all
# firing and resolved alerts to Alertecho
route:
  group_wait: 15s
  group_interval: 30s
  repeat_interval: 30m
  receiver: default
receivers:
  - name: default
    webhook_configs:
      - send_resolved: true
        url: http://alertecho:9095/alerts
