name: continuous integration

on:
  push:
    branches:
      - master
      - main
      - feature/**
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin
        cache: 'maven'

    - name: Build JAR from Maven
      run: mvn --batch-mode --no-transfer-progress clean verify

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - uses: actions/checkout@v4

    - name: Build Docker Image
      uses: docker/build-push-action@v6
      with:
        push: false
